package ca.etsmtl.applets.repository.data.api.response.mapper

import ca.etsmtl.applets.repository.data.api.response.signets.ApiSignetsData
import ca.etsmtl.applets.repository.data.api.response.signets.ApiSignetsModel
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.Moshi
import com.squareup.moshi.Types
import java.lang.reflect.ParameterizedType
import java.lang.reflect.Type

/**
 * Created by Sonphil on 26-04-18.
 */

internal class SignetsApplicationJsonAdapterFactory : ApplicationJsonAdapterFactory() {
    companion object {
        private val KOTSHI_APPLICATION_ADAPTER_FACTORY_INSTANCE = KotshiApplicationJsonAdapterFactory()
    }

    override fun create(type: Type, annotations: MutableSet<out Annotation>, moshi: Moshi): JsonAdapter<*>? {
        val rawType = Types.getRawType(type)

        return if (rawType == ApiSignetsModel::class.java && type is ParameterizedType) {
            val subType = type.actualTypeArguments.first()
            val adapter: JsonAdapter<out ApiSignetsData> = moshi.adapter(subType)

            ApiSignetsModelAdapter(adapter)
        } else { // If not, use an adapter generated by Kotshi
            KOTSHI_APPLICATION_ADAPTER_FACTORY_INSTANCE.create(type, annotations, moshi)
        }
    }
}