platform :ios, '11.2'

target 'ETSMobile' do
  use_frameworks!

  # Pods for ETSMobile
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftLint'

  target 'ETSMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ETSMobileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
