language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by the project
    - build-tools-28.0.2

    # The SDK version used to compile the project
    - android-28
    - android-21

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-28

    # System images to run emulators
    - sys-img-armeabi-v7a-android-28
    - sys-img-armeabi-v7a-android-21

before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "platforms;android-27"
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew assembleDebug -PdisablePreDex
  - ./gradlew ktlintCheck
  - ./gradlew test
  - ./gradlew connectedAndroidTest --info

notifications:
  slack:
    rooms:
        secure: fjWK0NbRt8ekhK9+IeHGQsLvlUuT6eyxZzdoerblOnxM4fR/qLZp9dvgcVnRX0s1i0eNusNP31A+hueO2SA7rNEd/HyMXITDoH0CzpooUolVs56kFjFoCWJvlZHeMkSivOTyfPX1rIdxxycf76LZvtmCH1q4H3MUzIYrsYmd6XlhTB6jB4JoTFm+4xfvbummr7JtP6O8DGC1z7/cG7VYl3VrcEOk44Rsuh80MsX36HYj6INhKV1aO6XlYgu1sahAZLQWN2/NLVeiFWseOWuhzCoUQwQeoivVORQjcroONisaauTBXmGbBkNyElOCvTg0WA3jYIJmSKq0Phx4eAxiJOJXQESY53UzZ0W7uDDIo3rIhrsGQqrBj6xciz4NafTTvgLcZmJkZDQCdK+W6L5nfV09TnWAEF+COY+VYWsWUuPOwxn5k+gIqZZFTJyEOwntq4pA0fI8ppV5oNvAhl2Az1cFxnrH+r/x6fbW8QEkAZZL2pLa5mvXfpgMi1aj2nkC2MxS7YTqNpttAssoiyZPUajdAt38WNrPN2mI04xINUke5xzGyWttPBrkt2xm6tJ+ZZtEhK1L5On1np74qGO5jRsLz5tQnsFXdV3qeERUzrbtRtH8eN7jYlu4k/00EAj8Dv6CVCFPTa8mvcapSIJFhq4WLqPRiPlQA453rCYm0fU=
    on_success: change
