# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ETSMobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ETSMobile

  target 'ETSMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ETSMobileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Firebase/Core'
end
