# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ETS-mobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Performance'

  # Pods for ETS-mobile
  pod 'Fabric', '~> 1.7.11'
  pod 'Crashlytics', '~> 3.10.7'

  target 'ETS-mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ETS-mobileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
